apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: eks-cluster-composition
  annotations:
    provider: aws
spec:
  crossplane:
    version: ">=v1.4.0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.29.0"
